spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0.0"

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Arjunan Ravi"
    email: "arjunanatwork@gmail.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 555-1235