apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardsdb-deployment
  labels:
    app: cardsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardsdb
  template:
    metadata:
      labels:
        app: cardsdb
    spec:
      containers:
        - name: cardsdb
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: CARDS_MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: eazybank-configmap
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: cardsdb
spec:
  selector:
    app: cardsdb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
