apiVersion: v1
kind: ConfigMap
metadata:
  name: eazybank-configmap
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
  CONFIGSERVER_APPLICATION_NAME: configserver
  EUREKA_APPLICATION_NAME: eurekaserver
  MYSQL_ROOT_PASSWORD: root
  ACCOUNTS_APPLICATION_NAME: accounts
  ACCOUNTS_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
  ACCOUNTS_OTEL_SERVICE_NAME: "accounts"
  ACCOUNTS_MYSQL_DATABASE: "accountsdb"
  LOANS_APPLICATION_NAME: loans
  LOANS_DATASOURCE_URL: "jdbc:mysql://loansdb:3307/loansdb"
  LOANS_OTEL_SERVICE_NAME: "loans"
  LOANS_MYSQL_DATABASE: "loansdb"
  CARDS_APPLICATION_NAME: cards
  CARDS_DATASOURCE_URL: "jdbc:mysql://cardsdb:3308/cardsdb"
  CARDS_OTEL_SERVICE_NAME: "cards"
  CARDS_MYSQL_DATABASE: "cardsdb"
  GATEWAY_APPLICATION_NAME: gatewayserver
  GATEWAY_SPRING_DATA_REDIS_CONNECT-TIMEOUT: "2s"
  GATEWAY_SPRING_DATA_REDIS_HOST: redis
  GATEWAY_SPRING_DATA_REDIS_PORT: "6379"
  GATEWAY_SPRING_DATA_REDIS_TIMEOUT: "1s"
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
