# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: arjunanravi/loans
  tag: v1.9.0

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

db:
  url: jdbc:mysql://loansdb:3307/loansdb

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
db_enabled: true
dbconfig_enabled: false